# Generated by Django 4.0.3 on 2022-04-16 01:53

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('sinopse', models.CharField(max_length=200)),
                ('min_faixaE', models.IntegerField()),
                ('year', models.DateField()),
                ('data_public', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(upload_to=api.models.banner_img)),
                ('titleimg', models.ImageField(upload_to=api.models.title_img)),
                ('trailer', models.FileField(upload_to=api.models.trailer_video)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
