# Generated by Django 4.0.3 on 2022-04-16 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seasongroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('seasonGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seasongroup')),
            ],
        ),
    ]
