# Generated by Django 4.0.3 on 2022-04-16 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_episode_animename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasongroup',
            old_name='number',
            new_name='season',
        ),
    ]
