# Generated by Django 4.0.3 on 2022-04-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_number_seasongroup_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='min_faixaE',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
