# Generated by Django 4.0.3 on 2022-04-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_anime_min_faixae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
