# Generated by Django 4.0.3 on 2022-04-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_episode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epsgroup',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
